// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4ydAHNMcySzTo2pCFfCzw9mySaOlTOcU',
    appId: '1:22690521576:web:83608437c4121f5dd0845d',
    messagingSenderId: '22690521576',
    projectId: 'myfitness-8059d',
    authDomain: 'myfitness-8059d.firebaseapp.com',
    storageBucket: 'myfitness-8059d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrNJpUUn8ZKppwM2vGKQQ8il4Va3ev3H8',
    appId: '1:22690521576:android:83fa96e55bd037d3d0845d',
    messagingSenderId: '22690521576',
    projectId: 'myfitness-8059d',
    storageBucket: 'myfitness-8059d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe_IR9J3LcW8Og9pvO2e5GVsthXEay3Vw',
    appId: '1:22690521576:ios:2e216ebfb59ed04bd0845d',
    messagingSenderId: '22690521576',
    projectId: 'myfitness-8059d',
    storageBucket: 'myfitness-8059d.firebasestorage.app',
    iosBundleId: 'com.example.myfitness',
  );
}
